---
# tasks file for brewmaster-backend

- block:
  - name: install dependencies
    become: true
    package:
      name: "{{ item }}"
      state: present
    loop: "{{ dependencies }}"
    tags: install

  - include_role:
      name: contrib/pip
    vars:
      pip_version: 3
      pip_packages:
        - pipenv

- name: GIT | clone backend repository
  git:
    repo: "{{ repo['url'] }}"
    force: true
    version: "{{ repo['version'] | default(omit) }}"
    dest: "{{ repo['dest'] }}"  # "{{ repo['dest'].startswith('/') | ternary(repo['dest'], ansible_env.HOME + repo['dest']) }}"
  tags: install

- name: PIPENV | install backend application
  become: true
  command: "pipenv install {{ develop | ternary('', '--deploy --system') }}"
  args:
    chdir: "{{ repo['dest'] }}"
  changed_when: false
  tags: install

- name: SYSTEMD | flask server repo absolute path
  command: "pwd"
  args:
    chdir: "{{ repo['dest'] }}"
  register: repo_absolute_path
  changed_when: false

- name: SYSTEMD | copy unit file
  become: true
  template:
    src: "flask_unit_file.service.j2"
    dest: "/etc/systemd/system/{{ backend_service['name'] }}.service"
  register: unit_file
  notify:
    - SYSTEMD | backend restart
    - SYSTEMD | daemon reload
  tags: configure

- name: SYSTEMD | start backend
  become: true
  systemd:
    name: "{{ backend_service['name'] }}"
    state: started
    enabled: true
  tags: configure
