---

- name: install dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ dependencies }}"
  tags: install

- name: GIT | clone brewmaster-frontend repository
  git:
    repo: "{{ repo['url'] }}"
    version: "{{ repo['version'] }}"
    dest: "{{ repo['dest'] }}"
  tags: install

- name: NPM | install
  npm:
    path: "{{ repo['dest'] }}"
    global: "{{ npm['global'] }}"
  tags: install

- name: SYSTEMD | copy unit file
  become: true
  template:
    src: "nodejs_unit_file.service.j2"
    dest: "/etc/systemd/system/{{ frontend_service['name'] }}.service"
  register: unit_file
  notify: SYSTEMD | ensure service is restarted
  tags: configure

- name: SYSTEMD | ensure systemctl daemon is reloaded
  become: true
  when: unit_file.changed
  systemd:
    daemin_reload: true
  tags: configure
