---

- name: install dependencies
  become: true
  package:
    name: "{{ item }}"
    state: present
  loop: "{{ dependencies }}"
  tags: install

- name: GIT | clone brewmaster-frontend repository
  git:
    repo: "{{ repo['url'] }}"
    version: "{{ repo['version'] | default(omit) }}"
    dest: "{{ repo['dest'] }}"
    force: true
  tags: install

- name: REPLACE | enable all host connection
  replace:
    path: "{{ repo['dest'] }}/package.json"
    regexp: 'webpack-dev-server --no-inline --open --hot --port 80'
    replace: 'webpack-dev-server --no-inline --open --hot --host 0.0.0.0 --port 80'
  tags: configure

- name: NPM | install
  npm:
    path: "{{ repo['dest'] }}"
  tags: install

- name: SYSTEMD | nodejs repo absolute path
  command: "pwd"
  args:
    chdir: "{{ repo['dest'] }}"
  register: repo_absolute_path
  changed_when: false

- name: SYSTEMD | copy unit file
  become: true
  template:
    src: "nodejs_unit_file.service.j2"
    dest: "/etc/systemd/system/{{ frontend_service['name'] }}.service"
  register: unit_file
  notify:
    - SYSTEMD | frontend restart
    - SYSTEMD | daemon reload
  tags: configure

- name: SYSTEMD | start frontend
  become: true
  systemd:
    name: "{{ frontend_service['name'] }}"
    state: started
    enabled: true
  tags: configure
