---

- hosts: pseudo-raspbian
  gather_facts: false
  pre_tasks:
    - name: RAW | install python3 on target
      become: true
      raw: >
        test -e {{ ansible_python_interpreter }} ||
        apt -y update && apt install -y python3
      tags: install

    - name: Gather facts
      setup:
  roles:
    - ansible-role-mqtt
