---

- name: SYSTEMD | frontend restart
  become: true
  systemd:
    name: "{{ frontend_service['name'] }}"
    state: restarted
  tags: configure

- name: SYSTEMD | daemon reload
  become: true
  when: unit_file.changed
  systemd:
    daemon_reload: true
  tags: configure
