---

# MQTT variables

# TimeScaleDB variables
debian_postgresql_database_user: postgres
debian_postgresql_database_password: brewmaster
debian_postgresql_database_name: brewmaster

# Backend aplication variables
backend_environments:
  DATABASE_USER: postgres
  DATABASE_PASSWORD: "{{ debian_postgresql_database_password }}"
  DATABSE_NAME: brewmaster
  SERVER_HOST: "0.0.0.0"
  BROKER_HOST: localhost

# Frontend aplication variables
