---

# MQTT variables

# TimeScaleDB variables
debian_postgresql_database_user: postgres
debian_postgresql_database_password: brewmaster
debian_postgresql_database_name: brewmaster

# Backend aplication variables
backend_environments:
  RUN_ENVIRONMENT: production
  DATABASE_USER: postgres
  DATABASE_PASSWORD: "{{ debian_postgresql_database_password }}"
  DATABSE_NAME: brewmaster
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: 5000
  BROKER_HOST: localhost

# Frontend aplication variables
frontend_nodejs_archive_url: "https://nodejs.org/dist/v12.16.2/node-v12.16.2-linux-armv7l.tar.gz"

frontend_environments:
  BACKEND_HOST: 192.168.0.80
  BACKEND_PORT: 5000

# TimescaleDB seed variables
database_servo_module_mac: "CC:50:E3:95:DC:24"
database_h300_module_mac: "CC:50:E3:96:19:7C"
database_rele_module_mac: "CC:50:E3:AA:AA:AA"  # TODO
database_thermometer_module_mac: "CC:50:E3:95:D6:D0"
