---

- name: Prepare
  hosts: all
  gather_facts: false
  become: true
  vars:
    ansible_deps: []
  tasks:
    - name: install python3
      raw: "apt update && apt install -y python3"

    - name: install ansible requirements
      become: true
      apt:
        name: "{{ item }}"
        state: present
      loop: "{{ ansible_deps }}"
