---

- hosts: brewmaster-pi
  vars:
    postgresql_seed_scripts:
      - mixer/seed_db_h300.sql
      - mixer/seed_db_measurements.sql
    # the order matters
    postgresql_target_tables:
      - measurement
      - device_datapoint
      - device
      - module_notification
      - module
      - device_type_datapoint
      - module_device_type
      - protocol
      - unit
      - notification
    postgresql_seed_dest: "/tmp/db_seeds"
    overwrite: false
  pre_tasks:
    - debug:
        msg: >
          This playbook requires a running TimescaleDB instance on specified
          socket.
  tasks:
    - name: create dir
      file:
        name: "{{ postgresql_seed_dest }}"
        state: directory

    - name: copy SQL scripts to remote
      template:
        src: "{{ item }}"
        dest: "{{ postgresql_seed_dest }}/{{ item.split('/')[-1] }}"
      loop: "{{ postgresql_seed_scripts }}"

    - name: delete all configuration tables
      when: overwrite
      become_user: "{{ debian_postgresql_database_user }}"
      postgresql_query:
        login_host: localhost
        login_password: "{{ debian_postgresql_database_password }}"
        db: "{{ debian_postgresql_database_name }}"
        query: "delete from {{ item }};"
      loop: "{{ postgresql_target_tables }}"

    - name: run SQL scripts on remote
      become_user: "{{ debian_postgresql_database_user }}"
      postgresql_query:
        login_host: localhost
        login_password: "{{ debian_postgresql_database_password }}"
        db: "{{ debian_postgresql_database_name }}"
        path_to_script: "{{ postgresql_seed_dest }}/{{ item.split('/')[-1] }}"
      loop: "{{ postgresql_seed_scripts }}"

    - name: restart backend to read new configuration
      become: true
      service:
        name: backend
        state: restarted
