---
# handlers file for brewmaster-backend

- name: SYSTEMD | backend restart
  become: true
  systemd:
    name: "{{ backend_service['name'] }}"
    state: restarted
  tags: configure

- name: SYSTEMD | daemon reload
  become: true
  when: unit_file.changed
  systemd:
    daemon_reload: true
  tags: configure
